### ISSUE TITLE
release 0.3.1 breaks semver

### ISSUE THREAD

**Issue by astraw** [plotters-rs/plotters-backend#4]
plotters-backend 0.3.1 introduced the `RotateAngle(f32)` variant into the `FontTransform` enum. This is a breaking change and plotters-canvas 0.3.0 now hits a compilation error with this release: 

```
error[E0004]: non-exhaustive patterns: `RotateAngle(_)` not covered
   --> /builds/straw/rust-cam/.cargo-proj/registry/src/github.com-1ecc6299db9ec823/plotters-canvas-0.3.0/src/canvas.rs:248:28
    |
248 |         let degree = match style.transform() {
    |                            ^^^^^^^^^^^^^^^^^ pattern `RotateAngle(_)` not covered
    | 
   ::: /builds/straw/rust-cam/.cargo-proj/registry/src/github.com-1ecc6299db9ec823/plotters-backend-0.3.1/src/text.rs:139:5
    |
139 |     RotateAngle(f32),
    |     ----------- not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `FontTransform`
```

Would it be possible to yank release 0.3.1 and re-release it as 0.4.0? Thanks!

**Comment by 38** [comment]
Thanks for reporting this. It was my mistake that mixing the breaking change with other stuff. 

The breaking change was reverted on current 0.3 release. 

Please let me know if this works, thanks again for your help!

**Comment by astraw** [comment]
Yes, you fixed the issue. Thanks for your fast work and thanks for plotters!
